### ISSUE TITLE
Fails silently when AWS creds are invalid

### ISSUE THREAD

**Issue by TheFirstAvenger** [OpenAperture/deployer#11]
```elixir
01:05:39.081 [error] Task #PID<0.317.0> started from #PID<0.285.0> terminating
Function: #Function<1.46913284/0 in OpenAperture.Deployer.MilestoneMonitor.monitor/3>
    Args: []
** (exit) an exception was raised:
    ** (RuntimeError) Invalid status code returned from AWS: "UnrecognizedClientException"
        (openaperture_deployer) lib/deployer/milestones/deploy_ecs.ex:72: OpenAperture.Deployer.Milestones.DeployEcs.deploy/1
        (openaperture_deployer) lib/deployer/milestone_monitor.ex:17: anonymous fn/4 in OpenAperture.Deployer.MilestoneMonitor.monitor/3
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
        (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3

```

**Comment by TheFirstAvenger** [comment]
Deployer task fails but workflow is never updated to reflect failed status.
